name: Lint
permissions:
  contents: read
  pull-requests: write

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - uses: psf/black@459562c71a725a0a58a7cb710bd4b68417df4496
        with:
          options: "--check --verbose"
          version: "~= 24.0"
