---
name: Release
permissions:
  contents: read
  pull-requests: write
  
on:
  push:
    branches:
      - release/*

jobs:
  release:
    name: Release
    if: startsWith(github.ref, 'refs/heads/release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Zip Release
        run: zip -x '*.git*' -r release.zip .

      - name: Extract owner and repo
        id: repo
        run: |
          echo "owner=${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "repository=${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@bdf3e6a99aa856b1f341bc37a6eee5e70b46d0c1
        with:
          versionSpec: '5.x'

      - name: Use GitVersion
        uses: gittools/actions/gitversion/execute@bdf3e6a99aa856b1f341bc37a6eee5e70b46d0c1
        id: gitversion

      - name: Install GitReleaseManager
        uses: gittools/actions/gitreleasemanager/setup@bdf3e6a99aa856b1f341bc37a6eee5e70b46d0c1
        with:
          versionSpec: '0.14.x'

      - name: Create release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/create@bdf3e6a99aa856b1f341bc37a6eee5e70b46d0c1
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          owner: ${{ env.owner }}
          repository: ${{ env.repository }}
          milestone: ${{ steps.gitversion.outputs.majorMinorPatch }}
          name: 'Release ${{ steps.gitversion.outputs.majorMinorPatch }}'
          assets: |
            release.zip

      - name: Publish release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/publish@bdf3e6a99aa856b1f341bc37a6eee5e70b46d0c1
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          owner: ${{ env.owner }}
          repository: ${{ env.repository }}
          tagName: ${{ steps.gitversion.outputs.majorMinorPatch }}

      - name: Close release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/close@bdf3e6a99aa856b1f341bc37a6eee5e70b46d0c1
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          owner: ${{ env.owner }}
          repository: ${{ env.repository }}
          milestone: ${{ steps.gitversion.outputs.majorMinorPatch }}
