name: test

on:
  workflow_dispatch:
  pull_request:

jobs:
  test_linux:
    name: "test on linux"
    runs-on: ubuntu-latest
    steps:
      - name: cuda-toolkit
        uses: Jimver/cuda-toolkit@v0.2.19    
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: setup
        run: |
          script/setup --dev
      - name: test
        run: |
          test $(script/run --version) = $(cat wyoming_faster_whisper/VERSION)
          script/lint
          script/test
