name: test

on:
  workflow_dispatch:
  pull_request:

jobs:
  test_linux:
    name: "Build and Test on Linux (self-hosted runner)"
    runs-on: self-hosted
    steps:
      - name: Install GCC For Ubuntu
        shell: bash
        if: runner.os == 'ubuntu'
        run: |
          sudo apt update
          sudo apt install -y \
            gcc \
            g++
      - name: Install CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.19
      - name: Setup Python
        uses: actions/setup-python@v5.3.0    
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup venv
        run: |
          script/setup --dev
      - name: Test Code
        run: |
          test $(script/run --version) = $(cat wyoming_faster_whisper/VERSION)
          script/lint
          script/test
